[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FF9500"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F7"
textColor = "#000000"
font = "sans serif"
